export default {
  GET_VINYL: 'GET_VINYL',
  GET_VINYL_SUCCESS: 'GET_VINYL_SUCCESS',
  GET_VINYL_FAIL: 'GET_VINYL_FAIL',

  GET_VINYLS: 'GET_VINYLS',
  GET_VINYLS_SUCCESS: 'GET_VINYLS_SUCCESS',
  GET_VINYLS_FAIL: 'GET_VINYLS_FAIL',
};
